# Generated by Django 2.2.1 on 2020-08-31 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20200831_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='data',
            new_name='images',
        ),
    ]
